package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"commentSystem/graph/model"
	"commentSystem/internal/models"
	"context"
)

// Level is the resolver for the level field.
func (r *commentResolver) Level(ctx context.Context, obj *models.Comment) (int32, error) {
	return int32(obj.CommentLevel), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *models.Comment) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*models.User, error) {
	return r.Store.CreateUser(ctx, input)
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*models.Post, error) {
	return r.Store.CreatePost(ctx, input)
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*models.Comment, error) {

	//for _, observer := range r.CommentPublishedChannel[input.PostID] {
	//	select {
	//	case observer <- &comment: // если есть место в буфере
	//	default:
	//		// если канал забит, пропускаем, чтобы не блокировать
	//	}
	//}
	//return &comment, nil

	comment, err := r.Store.CreateComment(ctx, input)
	if err != nil {
		return nil, err
	}

	return comment, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *models.Post) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(
	ctx context.Context,
	obj *models.Post,
	limit *int32,
	offset *int32,
	level *int32,
) ([]*models.Comment, error) {
	comments, err := r.Store.GetCommentsByPostID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	return flattenCommentsAsTree(comments, limit, offset, level), nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*models.Post, error) {
	return r.Store.GetPosts(ctx)
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*models.Post, error) {
	return r.Store.GetPostByID(ctx, id)
}

// CommentPublished is the resolver for the commentPublished field.
func (r *subscriptionResolver) CommentPublished(ctx context.Context, postID int) (<-chan *models.Comment, error) {
	commentEvent := make(chan *models.Comment, 10) // увеличил буфер

	// Добавляем канал в карту подписчиков
	r.mu.Lock() // используем mutex для безопасности
	r.CommentPublishedChannel[postID] = append(r.CommentPublishedChannel[postID], commentEvent)
	r.mu.Unlock()

	// Горутинка для удаления канала при отключении клиента
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		defer r.mu.Unlock()
		subs := r.CommentPublishedChannel[postID]
		for i, ch := range subs {
			if ch == commentEvent {
				r.CommentPublishedChannel[postID] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
	}()

	return commentEvent, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
