type User {
  id: ID!
  username: String!
}

type Post {
  id: ID!
  userId: ID!
  content: String!
  allowComment: Boolean!
  createdAt: Timestamp!
}

type Comment {
    id: ID!
    replyCommentId: ID
    postId: ID!
    userId: ID!
    content: String!
    createdAt: Timestamp!
}

input NewUser {
    username: String!
}

input NewPost {
    userId: ID!
    content: String!
    allowComment: Boolean = true
}

input NewComment {
    replyCommentId: ID
    postId: ID!
    userId: ID!
    content: String!
}

type Mutation {
  createUser(input: NewUser!): User!

  createPost(input: NewPost!): Post!

  createComment(input: NewComment!): Comment!
}

type Query {
    posts: [Post!]!
    post(id: ID!): Post
}

scalar Timestamp
