type User {
  id: ID!
  username: String!
}

type Post {
  id: ID!
  userID: ID!
  content: String!
  allowComment: Boolean!
  createdAt: Timestamp!
  comments(limit: Int = 10, offset: Int = 0, level: Int = 10): [Comment!]!
}

type Comment {
    id: ID!
    replyCommentID: ID
    postID: ID!
    userID: ID!
    content: String!
    level: Int!
    createdAt: Timestamp!
    replies: [Comment!]!
}

input NewUser {
    username: String!
}

input NewPost {
    userID: ID!
    content: String!
    allowComment: Boolean = true
}

input NewComment {
    replyCommentID: ID
    postID: ID!
    userID: ID!
    content: String!
}

type Mutation {
  createUser(input: NewUser!): User!

  createPost(input: NewPost!): Post!

  createComment(input: NewComment!): Comment!
}

type Query {
    posts: [Post!]!
    post(postID: ID!): Post
}

type Subscription {
    commentPublished(postID: ID!): Comment!
}

scalar Timestamp
