package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"commentSystem/graph/model"
	"commentSystem/internal/models"
	"context"
)

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *models.Comment) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*models.User, error) {
	var user models.User

	query := `INSERT INTO person (username) VALUES ($1) returning person_id, username;`

	err := r.DB.QueryRowxContext(ctx, query, input.Username).StructScan(&user)

	if err != nil {
		return nil, err
	}
	return &user, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*models.Post, error) {
	_, err := r.GetUserByID(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	var post models.Post

	query := `INSERT INTO post (person_id, content, allow_comment) VALUES ($1, $2, $3) returning post_id, person_id, content, allow_comment, created_at;`

	err = r.DB.QueryRowxContext(ctx, query, input.UserID, input.Content, input.AllowComment).StructScan(&post)

	if err != nil {
		return nil, err
	}
	return &post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*models.Comment, error) {
	_, err := r.GetUserByID(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	_, err = r.GetPostByID(ctx, input.PostID)
	if err != nil {
		return nil, err
	}

	var comment models.Comment

	query := `INSERT INTO comment (reply_comment_id, post_id, person_id, content) VALUES ($1, $2, $3, $4) returning comment_id, reply_comment_id, post_id, person_id, content, created_at;`

	err = r.DB.QueryRowxContext(ctx, query, input.ReplyCommentID, input.PostID, input.UserID, input.Content).StructScan(&comment)

	if err != nil {
		return nil, err
	}
	return &comment, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *models.Post) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*models.Post, error) {
	var posts []*models.Post

	query := `SELECT post_id, person_id, content, allow_comment, created_at FROM post;`
	err := r.DB.Select(&posts, query)

	if err != nil {
		return nil, err
	}

	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*models.Post, error) {
	post, err := r.GetPostByID(ctx, id)
	if err != nil {
		return nil, err
	}

	var comments []*models.Comment
	query := `
        WITH RECURSIVE comment_tree AS (
            SELECT comment_id, post_id, person_id, content, reply_comment_id, created_at
            FROM comment
            WHERE post_id = $1 AND reply_comment_id IS NULL
            UNION ALL
            SELECT c.comment_id, c.post_id, c.person_id, c.content, c.reply_comment_id, c.created_at
            FROM comment c
            INNER JOIN comment_tree ct ON c.reply_comment_id = ct.comment_id
        )
        SELECT * FROM comment_tree ORDER BY created_at
    `
	err = r.DB.Select(&comments, query, id)
	if err != nil {
		return nil, err
	}

	post.Comments = buildCommentTree(comments)
	return post, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
