package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"commentSystem/graph/model"
	"commentSystem/internal/models"
	"context"
	"fmt"
)

// Level is the resolver for the level field.
func (r *commentResolver) Level(ctx context.Context, obj *models.Comment) (int32, error) {
	return int32(obj.CommentLevel), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *commentResolver) CreatedAt(ctx context.Context, obj *models.Comment) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*models.User, error) {
	var user models.User

	query := `INSERT INTO person (username) VALUES ($1) returning person_id, username;`

	err := r.DB.QueryRowxContext(ctx, query, input.Username).StructScan(&user)

	if err != nil {
		return nil, err
	}
	return &user, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.NewPost) (*models.Post, error) {
	_, err := r.GetUserByID(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	var post models.Post

	query := `INSERT INTO post (person_id, content, allow_comment) VALUES ($1, $2, $3) returning post_id, person_id, content, allow_comment, created_at;`

	err = r.DB.QueryRowxContext(ctx, query, input.UserID, input.Content, input.AllowComment).StructScan(&post)

	if err != nil {
		return nil, err
	}
	return &post, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.NewComment) (*models.Comment, error) {
	_, err := r.GetUserByID(ctx, input.UserID)
	if err != nil {
		return nil, err
	}

	post, err := r.GetPostByID(ctx, input.PostID)
	if err != nil {
		return nil, err
	}

	if !(*post.AllowComment) {
		return nil, fmt.Errorf("the user with id %d has disabled comments", input.UserID)
	}

	var comment models.Comment
	var replyCommentLevel = 1
	var commentLevel = 1

	if input.ReplyCommentID != nil {
		query := `SELECT comment_level FROM comment WHERE comment_id = $1`
		err := r.DB.GetContext(ctx, &replyCommentLevel, query, *input.ReplyCommentID)
		if err != nil {
			return nil, fmt.Errorf("comment with id %d not found", *input.ReplyCommentID)
		}
		commentLevel = replyCommentLevel + 1
	}
	query := `INSERT INTO comment (reply_comment_id, comment_level, post_id, person_id, content) VALUES ($1, $2, $3, $4 ,$5) returning comment_id, reply_comment_id, comment_level, post_id, person_id, content, created_at;`

	err = r.DB.QueryRowxContext(ctx, query, input.ReplyCommentID, commentLevel, input.PostID, input.UserID, input.Content).StructScan(&comment)

	if err != nil {
		return nil, err
	}

	//for _, observer := range r.CommentPublishedChannel[input.PostID] {
	//	select {
	//	case observer <- &comment: // если есть место в буфере
	//	default:
	//		// если канал забит, пропускаем, чтобы не блокировать
	//	}
	//}
	return &comment, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *models.Post) (*models.Timestamp, error) {
	t := models.Timestamp(obj.CreatedAt)
	return &t, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *models.Post, limit *int32, offset *int32) ([]*models.Comment, error) {
	var comments []*models.Comment

	query := `
		SELECT comment_id, post_id, reply_comment_id, comment_level, person_id, content, created_at
		FROM comment
		WHERE post_id = $1
		ORDER BY created_at ASC
	`

	err := r.DB.SelectContext(ctx, &comments, query, obj.ID)
	if err != nil {
		return nil, err
	}

	ordered := flattenCommentsAsTree(comments)

	var l int32 = int32(len(ordered))
	var o int32 = 0

	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	if o > int32(len(ordered)) {
		return []*models.Comment{}, nil
	}

	end := o + l
	if end > int32(len(ordered)) {
		end = int32(len(ordered))
	}

	return ordered[o:end], nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*models.Post, error) {
	var posts []*models.Post

	query := `SELECT post_id, person_id, content, allow_comment, created_at FROM post;`
	err := r.DB.Select(&posts, query)

	if err != nil {
		return nil, err
	}

	return posts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int) (*models.Post, error) {
	return r.GetPostByID(ctx, id)
}

// CommentPublished is the resolver for the commentPublished field.
func (r *subscriptionResolver) CommentPublished(ctx context.Context, postID int) (<-chan *models.Comment, error) {
	commentEvent := make(chan *models.Comment, 10) // увеличил буфер

	// Добавляем канал в карту подписчиков
	r.mu.Lock() // используем mutex для безопасности
	r.CommentPublishedChannel[postID] = append(r.CommentPublishedChannel[postID], commentEvent)
	r.mu.Unlock()

	// Горутинка для удаления канала при отключении клиента
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		defer r.mu.Unlock()
		subs := r.CommentPublishedChannel[postID]
		for i, ch := range subs {
			if ch == commentEvent {
				r.CommentPublishedChannel[postID] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
	}()

	return commentEvent, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
