// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewComment struct {
	ReplyCommentID *int   `json:"replyCommentID,omitempty"`
	PostID         int    `json:"postID"`
	UserID         int    `json:"userID"`
	Content        string `json:"content"`
}

type NewPost struct {
	UserID       int    `json:"userID"`
	Content      string `json:"content"`
	AllowComment *bool  `json:"allowComment,omitempty"`
}

type NewUser struct {
	Username string `json:"username"`
}

type Query struct {
}

type Subscription struct {
}
